#!/usr/bin/env bash
# =============================================================================
# install-shellkeep.sh — Install or update ShellKeep on VPS
# =============================================================================
# Location on VPS: /opt/infra/apps/shellkeep/install-shellkeep.sh
#
# This script:
#   1. Creates the application directory structure
#   2. Clones (or pulls) the ShellKeep repository
#   3. Validates that .env exists
#   4. Generates production compose.yml and nginx proxy config
#   5. Builds images and runs Prisma migrations
#   6. Starts all services (api, web, nginx)
#   7. Verifies service health
#
# Usage:
#   cd /opt/infra/apps/shellkeep
#   chmod +x install-shellkeep.sh
#   ./install-shellkeep.sh
#
# For updates, just run the script again. It pulls latest code,
# rebuilds images, and runs any new migrations.
#
# Prerequisites:
#   - Docker and Docker Compose installed
#   - External PostgreSQL server accessible (via devnet Docker network)
#   - devnet Docker network created: docker network create devnet
#   - .env file with production values
# =============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
SHELLKEEP_DIR="/opt/infra/apps/shellkeep"
REPO_DIR="${SHELLKEEP_DIR}/repo"
REPO_URL="https://github.com/marinoscar/shellkeep.git"
BRANCH="main"
DOMAIN="shellkeep.marin.cr"
HOST_PORT="8323"

log() { echo "[shellkeep] $*"; }

# ---------------------------------------------------------------------------
# Step 1: Create directory structure
# ---------------------------------------------------------------------------
log "============================================"
log " ShellKeep Installer"
log "============================================"
log ""
log "[1/7] Setting up directories..."

mkdir -p "${SHELLKEEP_DIR}"

log "  Directories ready."

# ---------------------------------------------------------------------------
# Step 2: Clone or pull the repository
# ---------------------------------------------------------------------------
log ""
log "[2/7] Fetching source code..."

if [ -d "${REPO_DIR}/.git" ]; then
    log "  Repository exists. Pulling latest from ${BRANCH}..."
    cd "${REPO_DIR}"
    git fetch origin
    git reset --hard "origin/${BRANCH}"
    cd "${SHELLKEEP_DIR}"
    log "  Updated to latest."
else
    log "  Cloning from ${REPO_URL}..."
    git clone --branch "${BRANCH}" "${REPO_URL}" "${REPO_DIR}"
    log "  Clone complete."
fi

# ---------------------------------------------------------------------------
# Step 3: Check .env exists
# ---------------------------------------------------------------------------
log ""
log "[3/7] Checking environment file..."

if [ ! -f "${SHELLKEEP_DIR}/.env" ]; then
    log ""
    log "  ERROR: .env file not found at ${SHELLKEEP_DIR}/.env"
    log ""
    log "  Create it from the template:"
    log "    cp ${REPO_DIR}/infra/compose/.env.example ${SHELLKEEP_DIR}/.env"
    log "    nano ${SHELLKEEP_DIR}/.env"
    log ""
    log "  Required values to set:"
    log "    - NODE_ENV=production"
    log "    - APP_URL=https://${DOMAIN}"
    log "    - POSTGRES_HOST (your PostgreSQL host on devnet)"
    log "    - POSTGRES_PASSWORD"
    log "    - JWT_SECRET (generate with: openssl rand -hex 32)"
    log "    - COOKIE_SECRET (generate with: openssl rand -hex 32)"
    log "    - ENCRYPTION_KEY (generate with: openssl rand -base64 32)"
    log "    - GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET"
    log "    - GOOGLE_CALLBACK_URL=https://${DOMAIN}/api/auth/google/callback"
    log "    - S3_BUCKET, S3_REGION, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY"
    log "    - INITIAL_ADMIN_EMAIL"
    log ""
    log "  Then run this script again."
    exit 1
fi

log "  .env file found."

# ---------------------------------------------------------------------------
# Step 4: Generate production compose.yml and proxy config
# ---------------------------------------------------------------------------
log ""
log "[4/7] Generating production configuration..."

# ---- compose.yml ----
# Production-ready Docker Compose file that:
#   - Binds nginx to 127.0.0.1:8323 (VPS proxy routes here)
#   - Connects to external devnet network for PostgreSQL access
#   - Uses an internal shellkeep-internal network for service-to-service
#   - Sets restart policies and resource limits

cat > "${SHELLKEEP_DIR}/compose.yml" << 'COMPOSE_EOF'
# =============================================================================
# ShellKeep — Production Docker Compose
# =============================================================================
# Generated by install-shellkeep.sh
# Do not edit manually — re-run the installer to regenerate.
# =============================================================================

services:
  # ---------------------------------------------------------------------------
  # Nginx — Internal reverse proxy (routes /api → api, / → web)
  # ---------------------------------------------------------------------------
  nginx:
    container_name: shellkeep-nginx
    image: nginx:alpine
    ports:
      - "127.0.0.1:8323:80"
    volumes:
      - ./repo/infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - web
    restart: unless-stopped
    networks:
      - shellkeep-internal
      - proxy

  # ---------------------------------------------------------------------------
  # API — NestJS Backend (Fastify) with SSH/tmux terminal management
  # ---------------------------------------------------------------------------
  api:
    container_name: shellkeep-api
    build:
      context: ./repo/apps/api
      dockerfile: Dockerfile
      target: production
    env_file:
      - .env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
    networks:
      - shellkeep-internal
      - devnet

  # ---------------------------------------------------------------------------
  # Web — React Frontend (static build served by Nginx)
  # ---------------------------------------------------------------------------
  web:
    container_name: shellkeep-web
    build:
      context: ./repo/apps/web
      dockerfile: Dockerfile
      target: production
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      - shellkeep-internal

# =============================================================================
# Networks
# =============================================================================
networks:
  # Internal network for service-to-service communication
  shellkeep-internal:
    driver: bridge

  # Shared VPS proxy network (external, created by /opt/infra/proxy)
  proxy:
    external: true

  # External network for PostgreSQL access (shared with other projects)
  devnet:
    external: true
COMPOSE_EOF

log "  compose.yml generated."

# ---- VPS proxy nginx config ----
# This file goes into /opt/infra/proxy/nginx/conf.d/ to route
# shellkeep.marin.cr traffic to the shellkeep-nginx container.

cat > "${SHELLKEEP_DIR}/shellkeep.conf" << NGINX_EOF
# =============================================================================
# shellkeep.marin.cr — VPS Reverse Proxy Config
# =============================================================================
# Generated by install-shellkeep.sh
# Copy to: /opt/infra/proxy/nginx/conf.d/shellkeep.conf
# =============================================================================

server {
    listen 443 ssl http2;
    server_name ${DOMAIN};

    ssl_certificate     /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # Terminal WebSocket — long-lived connections for SSH sessions
    location /api/terminal/ws {
        proxy_pass http://shellkeep-nginx;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_connect_timeout 60s;
        proxy_send_timeout 3600s;
        proxy_read_timeout 3600s;
        proxy_buffering off;
    }

    # API routes
    location /api {
        proxy_pass http://shellkeep-nginx;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_connect_timeout 60s;
        proxy_send_timeout 120s;
        proxy_read_timeout 120s;
    }

    # Frontend (React SPA)
    location / {
        proxy_pass http://shellkeep-nginx;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}

# HTTP → HTTPS redirect
server {
    listen 80;
    server_name ${DOMAIN};

    # ACME challenge (Let's Encrypt)
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://\$server_name\$request_uri;
    }
}
NGINX_EOF

log "  shellkeep.conf generated."

# ---------------------------------------------------------------------------
# Step 5: Build images and run migrations
# ---------------------------------------------------------------------------
log ""
log "[5/7] Building images..."

cd "${SHELLKEEP_DIR}"
docker compose build

log "  Images built."

log ""
log "  Running database migrations..."

docker compose run --rm -T api sh -c \
    "npx prisma migrate deploy 2>/dev/null || echo 'Schema already up to date'"

log "  Migrations complete."

# ---------------------------------------------------------------------------
# Step 6: Start all services
# ---------------------------------------------------------------------------
log ""
log "[6/7] Starting all services..."

docker compose up -d

log "  All containers started."

# Wait for API to be ready
log "  Waiting for API to initialize..."
API_READY=false
for i in $(seq 1 60); do
    if docker exec shellkeep-api wget -qO- http://localhost:3000/api/health/live >/dev/null 2>&1; then
        API_READY=true
        break
    fi
    sleep 2
done

if [ "${API_READY}" = "false" ]; then
    log "  WARNING: API health check did not pass within 120 seconds."
    log "  Check logs: docker compose logs api"
fi

# ---------------------------------------------------------------------------
# Step 7: Verify health
# ---------------------------------------------------------------------------
log ""
log "[7/7] Verifying services..."
sleep 3

# Check containers are running
RUNNING=$(docker compose ps --format '{{.Name}}' 2>/dev/null | wc -l)
log "  Containers running: ${RUNNING}"

# Check API health
API_STATUS=$(docker exec shellkeep-api wget -qO- http://localhost:3000/api/health/live 2>/dev/null || echo "FAIL")
if echo "${API_STATUS}" | grep -qi "ok\|status\|healthy"; then
    log "  API health:    OK"
else
    log "  API health:    WARN (response: ${API_STATUS})"
    log "                 Check: docker compose logs api"
fi

log ""
log "============================================"
log " ShellKeep installation complete!"
log "============================================"
log ""
log " Internal URL: http://127.0.0.1:${HOST_PORT}"
log " External URL: https://${DOMAIN}"
log ""
log " If this is the FIRST install, complete these steps:"
log ""
log "   1. Copy proxy config to the VPS reverse proxy:"
log "      cp ${SHELLKEEP_DIR}/shellkeep.conf /opt/infra/proxy/nginx/conf.d/"
log ""
log "   2. Issue TLS certificate:"
log "      certbot certonly --webroot -w /opt/infra/proxy/webroot \\"
log "        -d ${DOMAIN} --config-dir /opt/infra/proxy/letsencrypt"
log ""
log "   3. Reload the VPS proxy:"
log "      docker exec proxy-nginx nginx -t"
log "      docker exec proxy-nginx nginx -s reload"
log ""
log "   4. Configure Google OAuth redirect URI:"
log "      https://${DOMAIN}/api/auth/google/callback"
log ""
log "   5. Verify:"
log "      curl https://${DOMAIN}/api/health/live"
log ""
log "============================================"
